<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_shippingDetail</name>
   <tag></tag>
   <elementGuidId>3946200c-25cd-4222-a23b-17e040b19cae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[.='Address']/following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[.='Address']/following-sibling::div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Iframe/iframe</value>
   </webElementProperties>
</WebElementEntity>
