<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_leftArrow</name>
   <tag></tag>
   <elementGuidId>a28005e2-8b86-4e58-b263-468cbd745791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@data-reactid='.0.0.0.1.1.0.0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[@data-reactid='.0.0.0.1.1.0.0']</value>
   </webElementProperties>
</WebElementEntity>
