<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phoneNumber</name>
   <tag></tag>
   <elementGuidId>c6aadba4-cc55-4e39-b11d-e22ae9a37656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-reactid='.0.0.1.0.3.0.0.2.1.0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-reactid='.0.0.1.0.3.0.0.2.1.0']</value>
   </webElementProperties>
</WebElementEntity>
