<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address</name>
   <tag></tag>
   <elementGuidId>d221eee8-8541-43f2-94f7-3b60147d19c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-reactid='.0.0.1.0.3.0.0.4.1.0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-reactid='.0.0.1.0.3.0.0.4.1.0']</value>
   </webElementProperties>
</WebElementEntity>
